apiVersion: v1
kind: Service
metadata:
  labels:
    app: hellopython
  name: hellopython
spec:
  ports:
  - name: http-hellopython
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: hellopython
